INSERT INTO usuario (name, password) VALUES ('test', '$2a$10$mUMaJhd2wDXe/hpGV2OrwOzXqwa29AGK3Q9o.LE9QAawmnjSRAyd2');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (1, 'Real Madrid', 'España', 'La Liga');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (2, 'FC Barcelona', 'España', 'La Liga');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (3, 'Manchester United', 'Inglaterra', 'Premier League');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (4, 'Liverpool FC', 'Inglaterra', 'Premier League');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (5, 'Juventus FC', 'Italia', 'Serie A');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (6, 'AC Milan', 'Italia', 'Serie A');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (7, 'Bayern Munich', 'Alemania', 'Bundesliga');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (8, 'Borussia Dortmund', 'Alemania', 'Bundesliga');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (9, 'Paris Saint-Germain', 'Francia', 'Ligue 1');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (10, 'Olympique de Marseille', 'Francia', 'Ligue 1');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (11, 'FC Porto', 'Portugal', 'Primeira Liga');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (12, 'Sporting CP', 'Portugal', 'Primeira Liga');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (13, 'Ajax Amsterdam', 'Países Bajos', 'Eredivisie');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (14, 'Feyenoord', 'Países Bajos', 'Eredivisie');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (15, 'Celtic FC', 'Escocia', 'Scottish Premiership');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (16, 'Rangers FC', 'Escocia', 'Scottish Premiership');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (17, 'Galatasaray SK', 'Turquía', 'Süper Lig');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (18, 'Fenerbahçe SK', 'Turquía', 'Süper Lig');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (19, 'FC Zenit Saint Petersburg', 'Rusia', 'Premier League Rusa');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (20, 'Spartak Moscow', 'Rusia', 'Premier League Rusa');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (21, 'SL Benfica', 'Portugal', 'Primeira Liga');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (22, 'Besiktas JK', 'Turquía', 'Süper Lig');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (23, 'SSC Napoli', 'Italia', 'Serie A');
INSERT INTO team (team_id, nombre, pais, liga) VALUES (24, 'Atlético Madrid', 'España', 'La Liga');